### PR TITLE
Various Package Updates

### PR DESCRIPTION
**Pull request by ReportMort**
This pull request covers a introduces some new functionality and enhances or fixes some old functions as well. Below is list of changes:

Close open connection from `rforcecom.insertBulkAttachments`
Add concurrency mode as option for `rforcecom.createBulkJob`
Fix Login Issue with ampersand by escaping which addresses Issue  https://github.com/hiratake55/RForcecom/issues/17
Add `rforcecom.logout` function
Add `rforcecom.bulkQuery` function for convenience
Add `queryAll` option to rforcecom.query so that deleted and archived records can be returned

### CODE REVIEW

**Comment by ReportMort** [comment]
@hiratake55 The build will not pass because in the Travis build 
 > Encrypted variables are not added to untrusted builds such as pull requests coming from another repository (http://docs.travis-ci.com/user/environment-variables/)

This causes the test for `rforcecom.login` to error.

**Comment by ReportMort** [comment]
Note that in test cases I've changed instanceURL as a system environment variable because it might change as well: Sys.getenv("RFORCECOM_INSTANCEURL")

**Comment by ax42** [comment]
I think logging in with the InstanceURL is probably incorrect (based on recent changes in SF).  I think the login should always be done to https://login.salesforce.com, and then the session should use the returned URL (which I think will include the instance).

I'm basing this on the fact that our organisation recently moved from one instance to another (instance split, we went from eu1 to eu4), so all the manually produced links in Chatter, which pointed to the instance, no longer worked.  The way to fix it is to make these links point to ```http://login.salesforce.com/OBJECTID``` and SF will figure it out.

See https://developer.salesforce.com/docs/atlas.en-us.api.meta/api/sforce_api_calls_login_loginresult.htm#topic-title

**Comment by hiratake55** [comment]
Hi @ReportMort 
Thank you for sending me new features, As you may understand the Travis CI test failure was caused by encrypted email and password. I had changed Travis setting for making disable run on pull request. Sorry for bothering you.

@ax42 
Thank your for valuable information, I'll fix in a next update. Alternatively, the below code is a workaround for solving the problem.

```
username <- "YOUR EMAIL"
password <- "YOUR PASS AND YOUR TOKEN"
instanceURL <- "https://login.salesforce.com/"
apiVersion <- "30.0"
session <- rforcecom.login(username, password, instanceURL, apiVersion)
session['instanceURL'] <- "https://YOUR SUBDOMAIN.salesforce.com/"
rforcecom.retrieve(session, "OBJECT NAME", FIELDS)
```

**Comment by ax42** [comment]
Thanks for the workaround -- the existing code seems to work, but depends on the user entering the correct instanceURL in their code.  The 'right' way seems to make that unnecessary (as you can always log in to login.salesforce.com, and salesforce will then tell you the instanceURL).

**Pull request merged**
