### PR TITLE
Adding Bulk API Functionality

### PR DESCRIPTION
**Pull request by ReportMort**
Assuming users of the RForcecom package will have the goal of performing mass data transformations against Salesforce data I believe it's a good addition to have Bulk API access to better facilitate those types of activities via R. The REST API has limits on the number of daily requests a user can make via the API. Typically this limit is in the thousands, which is a problem if the user wants to insert/update/delete hundreds of thousands or millions of records via the API. The Bulk API allows the user to submit up to 10,000 records in a single request, which circumvents many issues that arise when calling the REST API repeatedly.

Thank you for your time and consideration in adding this functionality to the RForcecom package. I'm happy to help in any way that would facilitate further development and maintenance.

### CODE REVIEW

**Comment by ReportMort** [comment]
Here is the outline of a working example:
```
# login
username <- "yourname@yourcompany.com"
password <- "YourPasswordSECURITY_TOKEN"
instanceURL <- "https://xx99.salesforce.com/"
apiVersion <- "27.0"
session <- rforcecom.login(username, password, instanceURL, apiVersion)

# create a sample data.frame of 1000 records
n <- 1000
data <- data.frame(Name=paste('New Record:', 1:n), stringsAsFactors=FALSE)

# create, run, and close Bulk API Job
# run an insert job into the Account object
job_info <- rforcecom.createBulkJob(session, operation='insert', object='Account')
# split into batche sizes of 500 (2 batches for our 1000 row sample dataset)
batches_info <- rforcecom.createBulkBatch(session, jobId=job_info$id, data, multiBatch = TRUE, batchSize=500)
# check on status of each batch
batches_status <- lapply(batches_info, FUN=function(x){rforcecom.checkBatchStatus(session, jobId=x$jobId, batchId=x$id)})
# get details on each batch
batches_detail <- lapply(batches_info, FUN=function(x){rforcecom.getBatchDetails(session, jobId=x$jobId, batchId=x$id)})
# close the job
close_job_info <- rforcecom.closeBulkJob(session, jobId=job_info$id)
```

**Comment by Btibert3** [comment]
I haven't had a chance to test the code myself, but I think this is a great direction.  Assuming the code works, it makes a ton of sense to have this functionality if there is a need (and there is) to do larger operations with R and SF.

**Comment by ReportMort** [comment]
Thanks @Btibert3 . I don't have a comprehensive test suite, but feel free install as-is and run some of the examples. Would love any feedback you're willing to provide.

```
library(devtools)
install_github('ReportMort/RForcecom/RForcecom', ref='feature/bulk-api')
library(RForcecom)
# examples at bottom of help
?RForcecom
```

**Comment by ReportMort** [comment]
@hiratake55 Have you had the chance to review this pull request to implement Bulk API functionality?

**Comment by hiratake55** [comment]
@ReportMort I would like to say very thank you for your contribution, I'll send them to CRAN once I take a unit test.

**Pull request merged**
