### PR TITLE
Rewrite XML Parsing for Query Recordsets

### PR DESCRIPTION
**Pull request by ReportMort**
This request changes the package to use one function called `query_parser` when parsing the results returned by Salesforce from SOQL queries. This was done to better handle foreign object  and child-parent nested relationships that SOQL queries can return.

I believe this methodology or another methodology should be deployed soon in order to quickly resolve the backlog of issues described in #23 

Link to `query_parser` code:
https://github.com/ReportMort/RForcecom/blob/query-refactor/R/rforcecom.utils.R

### CODE REVIEW

**Comment by ax42** [comment]
We're seeing the same issue -- would be great if this pull request could be integrated asap.

**Comment by nelsonauner** [comment]
@ReportMort 
After getting the same error as described in #23 (` Error: All inputs to rbind.fill must be data.frames`) , I now get a new error:

`Error in t.default(unlist(x[setdiff(seq.int(length(x)), c(list_col, attr_col))])) : 
  argument is not a matrix `

 Is there an easy fix for this? 
If not, I can open an issue + put in more steps to reproduce

**Comment by hiratake55** [comment]
@nelsonauner The patch merged but it is not on the CRAN now. Please try the code from github or please wait just a few days, I will upload the current head version to CRAN.

**Comment by nelsonauner** [comment]
This error was encountered with RForcecom_0.9
installed today using `github_install("hiratake55/RForcecom")`

**Comment by ReportMort** [comment]
@nelsonauner Could you add some more detail and we'll go from there? Thanks.

**Comment by nelsonauner** [comment]
@ReportMort @hiratake55 
Sure, I've opened an issue at #37

**Pull request merged**
